# Generated by Django 5.2.6 on 2025-09-29 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_player_goals_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_of', to='api.player'),
        ),
    ]
