# Generated by Django 5.2.6 on 2025-09-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_team_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='player_id_photos/'),
        ),
    ]
