# Generated by Django 5.2.6 on 2025-09-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_player_id_number_player_id_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id_number',
            field=models.CharField(default='0000', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='id_photo',
            field=models.ImageField(null=True, upload_to='player_id_photos/'),
        ),
    ]
